# Generated by Django 5.2.8 on 2025-12-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactpage_from_address_contactpage_subject_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image_caption',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gif',
            field=models.ForeignKey(blank=True, help_text='Uploader un GIF animé pour illustrer la page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='GIF de la section À propos'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gif_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Légende du GIF'),
        ),
    ]
