# Generated by Django 5.2.8 on 2025-12-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_aboutpage_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='gif',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='gif_caption',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Photo d’équipe ou image illustrative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de la section À propos'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Légende de l’image'),
        ),
    ]
