# Generated by Django 5.2.9 on 2025-12-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_galeriepage_galerieimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerieimage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='galerieimage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
